"""Add invite_code column to WG

Revision ID: 245d562ad608
Revises: 
Create Date: 2026-01-10 11:41:11.947649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245d562ad608'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WG', schema=None) as batch_op:
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###
