"""add created_at to ShoppingItem

Revision ID: 67355bf1e881
Revises: aade67afb5a8
Create Date: 2026-01-15 13:00:31.651540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67355bf1e881'
down_revision = 'aade67afb5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ACTIVITY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ACTIVITY_activity_id'))
        batch_op.create_index(batch_op.f('ix_ACTIVITY_activity_id'), ['activity_id'], unique=True)

    with op.batch_alter_table('SHOPPING_ITEM', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_user_id'))
        batch_op.create_index(batch_op.f('ix_USER_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_user_id'))
        batch_op.create_index(batch_op.f('ix_USER_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('SHOPPING_ITEM', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ACTIVITY', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ACTIVITY_activity_id'))
        batch_op.create_index(batch_op.f('ix_ACTIVITY_activity_id'), ['activity_id'], unique=False)

    # ### end Alembic commands ###
