"""add activity_participants to db

Revision ID: 6c557be03476
Revises: 904c3bd6ca69
Create Date: 2026-01-06 14:03:15.248360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c557be03476'
down_revision = '904c3bd6ca69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ACTIVITY_PARTICIPANTS',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['ACTIVITY.activity_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'user_id')
    )
    with op.batch_alter_table('ACTIVITY', schema=None) as batch_op:
        batch_op.drop_column('participants')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ACTIVITY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants', sa.VARCHAR(), nullable=True))

    op.drop_table('ACTIVITY_PARTICIPANTS')
    # ### end Alembic commands ###
