"""add date to activity

Revision ID: 83de07b7ce81
Revises: 
Create Date: 2026-01-05 14:00:24.514653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83de07b7ce81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.batch_alter_table(sa.Column('password_hash', sa.DateTime(), nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('IDEA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('ACTIVITY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_datetime', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('start_datetime', sa.DATETIME(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
