"""add participants to activity

Revision ID: 904c3bd6ca69
Revises: 83de07b7ce81
Create Date: 2026-01-05 15:57:35.147529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904c3bd6ca69'
down_revision = '83de07b7ce81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ACTIVITY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants', sa.String(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ACTIVITY', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('participants')

    # ### end Alembic commands ###
